version: "3.9"

services:
  db:
    image: postgres:14-alpine3.21
    container_name: rag-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [ragnet]

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    restart: unless-stopped
    ports: ["6333:6333", "6334:6334"]
    volumes:
      - qdrant_storage:/qdrant/storage
      - qdrant_snapshots:/qdrant/snapshots
    networks: [ragnet]

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: rag-api
    restart: unless-stopped
    env_file: [.env]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      QDRANT_URL: ${QDRANT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      S3_BUCKET: ${S3_BUCKET}
      
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_started
    ports: ["8000:8000"]
    networks: [ragnet]
    volumes:
      - ../api:/app
    # Keep container running for manual execution
    command: sh -c "while true; do sleep 1000; done"

  webui:
    build:
      context: ../webui
      dockerfile: Dockerfile
    container_name: rag-webui
    restart: unless-stopped
    ports: ["3000:3000"]
    networks: [ragnet]
    volumes:
      - ../webui:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    # Keep container running for manual execution
    command: sh -c "while true; do sleep 1000; done"

networks:
  ragnet:

volumes:
  pgdata:
  qdrant_storage:
  qdrant_snapshots:
