version: "3.9"

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: rag-api
    env_file: [.env]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      QDRANT_URL: ${QDRANT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      S3_BUCKET: ${S3_BUCKET}
      
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    ports: ["8000:8000"]
    networks: [ragnet]
    volumes:
      - ../api:/app

  webui:
    build:
      context: ../webui
      dockerfile: Dockerfile
    container_name: rag-webui
    restart: unless-stopped
    ports: ["3000:3000"]
    networks: [ragnet]
    volumes:
      - ../webui:/app
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
      
  worker:
    build:
      context: ../rag
      dockerfile: Dockerfile
    container_name: rag-worker
    volumes:
      - ../rag:/app
      - workerdata:/root/.cache/huggingface
    depends_on:
      - kafka
      - qdrant
    environment:
      KAFKA_BROKER_URL: kafka:9092
      QDRANT_URL: http://qdrant:6333
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
    networks: [ragnet]
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Worker is in idle mode, waiting...";
        tail -f /dev/null

  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollamadata:/root/.ollama
    networks: [ragnet]                        

networks:
  ragnet:
    driver: bridge

volumes:
  workerdata:
  ollamadata: